### ISSUE TITLE
리액트 문서 한국어 번역 프로젝트

### ISSUE THREAD

**Issue by sairion** [reactkr/react#1]
### 번역 to-dos
- [x] 01-why-react.md
- [ ] 02-displaying-data.md
- [ ] 02.1-jsx-in-depth.md
- [ ] 02.2-jsx-spread.md
- [ ] 02.3-jsx-gotchas.md
- [ ] 03-interactivity-and-dynamic-uis.md
- [ ] 04-multiple-components.md
- [ ] 05-reusable-components.md
- [ ] 06-transferring-props.md
- [ ] 07-forms.md
- [ ] 08-working-with-the-browser.md
- [ ] 08.1-more-about-refs.md
- [ ] 09-tooling-integration.md
- [ ] 10-addons.md
- [ ] 10.1-animation.md
- [ ] 10.2-form-input-binding-sugar.md
- [ ] 10.3-class-name-manipulation.md
- [ ] 10.4-test-utils.md
- [ ] 10.5-clone-with-props.md
- [ ] 10.6-update.md
- [ ] 10.7-pure-render-mixin.md
- [ ] 10.8-perf.md
- [ ] complementary-tools.md
- [ ] examples.md
- [ ] flux-overview.md
- [ ] flux-todo-list.md
- [ ] getting-started.md
- [ ] ref-01-top-level-api.md
- [ ] ref-02-component-api.md
- [ ] ref-03-component-specs.md
- [ ] ref-04-tags-and-attributes.md
- [ ] ref-05-events.md
- [ ] ref-06-dom-differences.md
- [ ] ref-07-special-non-dom-attributes.md
- [ ] ref-08-reconciliation.md
- [ ] ref-09-glossary.md
- [ ] thinking-in-react.md
- [ ] tutorial.md
- [ ] videos.md

**Comment by sairion** [comment]
Closing, the issue will be continued to https://github.com/reactkr/discuss/issues/4

**Comment by dittos** [comment]
test
