### ISSUE TITLE
Contributor license agreement

### ISSUE THREAD

**Issue by marocchino** [reactkr/react#55]
[가이드](https://github.com/facebook/react/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)읽으시고 
https://code.facebook.com/cla 에서 등록해주시면 됩니다.
- [x] @marocchino
- [x] @dittos 
- [x] @arkist 
- [x] @sairion 
- [x] @jeyraof 
- [x] @seoh
- [x] @jiyeonseo
- [x] @dalinaum

**Comment by dalinaum** [comment]
```
The 'Email' and 'GitHub' values have been registered on this form before. If you would like to update an existing contributor account, please email cla@fb.com with your details.
```

아마 fb-adb 때문에 등록했나 봅니다.

**Comment by marocchino** [comment]
:+1:
