### ISSUE TITLE
GitHub Pages 제거 (임시)

### ISSUE THREAD

**Issue by dittos** [reactkr/react#65]
이전 버전의 문서라 혼란을 일으킬 수 있을 것 같습니다. `gh-pages` 브랜치를 임시로 이름 변경하고 영문 문서로 리다이렉트 할까 하는데 어떻게 생각하시는지요?

https://www.facebook.com/groups/webfrontend/permalink/836625299815540/

**Comment by arkist** [comment]
이미 공유된 링크들이 문제가 되지 않을까요?
안내문구를 노출해 주던가 공식 사이트에 한글문서 올바른 페이지로 보내줄 수 있다면 좋을텐데.. 뭘하든 손이 들긴 하겠네요

**Comment by sairion** [comment]
정확한 공식 문서로 보낼 수 있는 방법이 있으면 괜찮을 것 같습니다.

**Comment by dittos** [comment]
redirect되도록 했습니다. https://github.com/reactkr/react/commit/b71043b97a500fbe03777249a508ace92e4e59b2

예시: https://reactkr.github.io/react/docs/getting-started-ko-KR.html -> https://facebook.github.io/react/docs/getting-started.html

기존 `gh-pages` 브랜치는 `gh-pages-old`에 남겨뒀습니다.
